name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: ryanccn/attic-action@v0
        with:
          endpoint: "https://cache.lukasl.dev/"
          cache: cartppole
          token: "${{ secrets.CACHE_SECRET }}"

      - name: ty
        run: nix run .#check
